### PR TITLE
Switched from darksky to wundergroud

### PR DESCRIPTION
**Pull request by KyeNormanGill**
Switched from darksky api to wundergrounds api.
Haven't tested it yet, i assume it works.

### CODE REVIEW

**Comment by iCrawl** [comment]
Whats the reason for this?
Wundergrounds only has 500 calls per day as opposed to 1000.
It also limits to 10 calls per minute.

**Comment by kurisubrooks** [comment]
Wunderground tends to have much, much more accurate data, but I tend to find DarkSky have much friendlier, developer-oriented APIs. Wunderground also tends to have some issues backend, so error catching is a must. This might be worth looking into, at least for Midori if not Commando and others too.

**Comment by iCrawl** [comment]
500 calls a day is def. a no-go for any public bot. And 5000 calls for 20$ is way too high, considering I only pay $0.1 for each 1000 more on Darksky.net.

The 10 calls /m limit seems stupid too, because on a public bot you get more than 10 weather requests per minute.

Leaving accuracy aside, every weather app has different sources to take their data from, so if you are concerned about that 1-5 degree difference, I guess.

Looking at the code it doesn't do anything more special than the darksky API.

**Comment by kurisubrooks** [comment]
Fair enough, just thought some data accuracy might be nicer to have, but given Wunderground's silly stance against developers I think i'm gonna have to close this one for now. Thanks for your effort @KyeNormanGill

**Comment by KyeNormanGill** [comment]
ಠ_ಠ

**Pull request closed without merging**
